"""update types

Revision ID: 1b2bccb246b5
Revises: 5e94de1447c9
Create Date: 2025-05-02 16:27:55.029494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b2bccb246b5'
down_revision: Union[str, None] = '5e94de1447c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nutrition', 'protein',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('nutrition', 'fat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('nutrition', 'carbohydrates',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('nutrition', 'calories',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('recommendation_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('statistics', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    op.alter_column('statistics', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('recommendation_history', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('nutrition', 'calories',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('nutrition', 'carbohydrates',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('nutrition', 'fat',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('nutrition', 'protein',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
