class ValidationError(Exception): ...


class NotFoundError(Exception): ...


class ForbiddenError(Exception): ...


class UserNutritionNotSetError(Exception): ...


class AudioToTextError(Exception): ...
